services:
  app:
    image: louislam/uptime-kuma:1
    container_name: '{{container_name}}'
    ports:
      - '{{host_port}}:3001'
    volumes:
      - '{{data_path}}:/app/data'
    restart: unless-stopped
